#!/bin/sh

set -e

trap clean 0 1 2 3 6

clean() {
  rm -rf Lex.hs *.{hi,o}
}

alex Lex.x

ghc Main.hs -o a.out
time ./a.out
exit

case "$1" in
  *.hs) ghci -XOverloadedStrings "$1";;
  *.x)  ghci -XOverloadedStrings 'Lex.hs';;
  *)    echo "cannot run '$1'";;
esac
