#!/bin/sh

set -e

trap clean 0 1 2 3 6

clean() {
  rm -f Lex.hs Parse.hs *.{hi,o} Main
}

alex Lex.x
happy Parse.y

runhaskell Test.hs

exit

case "$1" in
  *.hs|*.x|*.y) ghci "${1%.*}.hs";;
  *)            echo "cannot run '$1'";;
esac

#python mcc.py

#python test_asm.py |ndisasm -b64 -
