#!/bin/sh

set -e

trap clean 0 1 2 3 6

clean() {
  rm -rf parser.ml{,i} lexer{,_}.ml *.cm{i,o}
}

ocamlyacc parser.mly
ocamllex lexer.mll

mv lexer.ml lexer_.ml

# https://stackoverflow.com/questions/30271173/print-tokenization-of-a-string
cat <<EOF >lexer.ml
let engine_ a b lexbuf =
  let res = Lexing.engine a b lexbuf in
  Printf.eprintf "Saw token: '%s'\n" (Lexing.lexeme lexbuf);
  res
EOF

sed 's/Lexing\.engine/engine_/g' lexer_.ml >>lexer.ml

ocamlc type.ml id.ml syntax.ml parser.mli parser.ml lexer.ml show.ml main.ml
rlwrap ./a.out <tests1.txt >tests2.txt 2>/dev/null

paste -d '\n' tests1.txt tests2.txt >../input.txt
echo '%' >>../input.txt
