#!/bin/sh

set -e

trap clean 0 1 2 3 6

clean() {
  rm -rf parser.ml{,i} lexer.ml *.cm{i,o}
}

ocamlyacc parser.mly
ocamllex lexer.mll

ocamlc type.ml id.ml syntax.ml parser.mli parser.ml lexer.ml m.ml typing.mli typing.ml s.ml kNormal.ml alpha.ml show.ml main.ml
rlwrap ./a.out <tests2.txt >out2.txt 2>/dev/null

paste -d '\n' tests2.txt out2.txt >../input.txt
echo '%' >>../input.txt
