#!/bin/sh

set -e

trap clean 0 1 2 3 6

clean() {
  rm -rf *.cm{i,o}
}

ocamlc util.ml error.ml token_kind.ml token.ml scanner.ml ast.ml parser.ml value.ml environment.ml interpreter.ml main.ml
#time python test.py |./a.out
rlwrap ./a.out
